dist: trusty
sudo: false
language: go
go:
- "1.x"
- master

install:
- go get github.com/kardianos/govendor

script:
- make test
- make vendor-status
- make fmtcheck
- make vet

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_deploy:
- make targets
